---
abstract: 'Validation::Class HTML Form Field Renderer'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Validation-Class-Plugin-FormFields
requires:
  File::Copy: 0
  File::ShareDir: 0
  Template: 0
  Validation::Class: 5.20
version: 0.30
